import {useEffect,useState} from 'react';import {ArrowRight,Check,MessageCircle,Phone,Send} from 'lucide-react';
const services=[
{code:'01',name:'Poster POS',ru:'Автоматизация ресторана: зал, столы, кухня, пречеки и управление продажами.',hy:'Ռեստորանի ավտոմատացում՝ սրահ, սեղաններ, խոհանոց, նախահաշիվներ և վաճառքի կառավարում։'},
{code:'02',name:'HDM / ՀԴՄ',ru:'Фискализация продажи напрямую в рабочем процессе кассы.',hy:'Վաճառքի ֆիսկալացում անմիջապես դրամարկղի աշխատանքային հոսքում։'},
{code:'03',name:'IDRAM QR',ru:'QR-оплата, связанная с заказом и суммой продажи.',hy:'QR վճարում՝ կապված պատվերի և վաճառքի գումարի հետ։'},
{code:'04',name:'CIA POS Lite',ru:'Лёгкая касса для небольших магазинов и торговых точек.',hy:'Թեթև դրամարկղ փոքր խանութների և առևտրային կետերի համար։'},
{code:'05',name:'ESC/POS Print',ru:'Печать чеков и пречеков на совместимых термопринтерах.',hy:'Կտրոնների և նախահաշիվների տպագրություն համատեղելի թերմոտպիչներով։'},
{code:'06',name:'API Integration',ru:'Связываем Poster, оплату, фискализацию и ваши внутренние сервисы.',hy:'Միացնում ենք Poster-ը, վճարումները, ֆիսկալացումը և ձեր ներքին ծառայությունները։'}];
function useLang(){const [lang,setLang]=useState<'ru'|'hy'>(()=>document.documentElement.lang==='hy'?'hy':'ru');useEffect(()=>{const o=new MutationObserver(()=>setLang(document.documentElement.lang==='hy'?'hy':'ru'));o.observe(document.documentElement,{attributes:true,attributeFilter:['lang']});return()=>o.disconnect()},[]);return lang}
export function ServicesDetail(){const lang=useLang(),hy=lang==='hy';return <section className="service-detail" id="services-detail"><div className="service-detail-head"><span className="eyebrow">CIA SOFT · SERVICES 0.1</span><h2>{hy?'Մեկ համակարգ։ Վեց գործիք։':'Одна система. Шесть инструментов.'}</h2><p>{hy?'Միացնում ենք միայն այն, ինչ իրականում պետք է ձեր բիզնեսին։':'Подключаем только то, что действительно нужно вашему бизнесу — от кассы до собственной интеграции.'}</p></div><div className="service-list">{services.map(s=><article key={s.code}><span>{s.code}</span><strong>{s.name}</strong><p>{s[lang]}</p><Check size={16}/></article>)}</div><a className="service-cta" href="#contact">{hy?'Հավաքել իմ համակարգը':'Собрать мою систему'} <ArrowRight size={16}/></a></section>}
export function ContactForm(){const lang=useLang(),hy=lang==='hy';const [sent,setSent]=useState(false);const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();setSent(true)};return <div className="lead-panel"><span className="eyebrow">CONTACT 0.1</span><h3>{hy?'Ստանալ առաջարկ ձեր բիզնեսի համար':'Получить решение для вашей точки'}</h3><p>{hy?'Թողեք կոնտակտը։ Կքննարկենք ձեր ընթացիկ համակարգը և կառաջարկենք անհրաժեշտ կազմը։':'Оставьте контакт. Обсудим вашу текущую систему и предложим нужную конфигурацию.'}</p>{sent?<div className="lead-success"><Check/><strong>{hy?'Շնորհակալություն':'Спасибо!'}</strong><span>{hy?'Ձեր տվյալները պատրաստ են ուղարկման։ Հաջորդ քայլում կմիացնենք CRM/Telegram։':'Форма готова. На следующем шаге подключим реальную отправку в CRM/Telegram.'}</span></div>:<form onSubmit={submit}><label>{hy?'Բիզնեսի անվանումը':'Название бизнеса'}<input required name="business" placeholder={hy?'Օր. My Cafe':'Например, My Cafe'}/></label><label>{hy?'Հեռախոս':'Телефон'}<input required name="phone" inputMode="tel" placeholder="+374 __ ___ ___"/></label><label>{hy?'Բիզնեսի տեսակը':'Тип бизнеса'}<select name="type" defaultValue="restaurant"><option value="restaurant">{hy?'Ռեստորան / սրճարան':'Ресторан / кафе'}</option><option value="retail">{hy?'Խանութ':'Магазин'}</option><option value="foodcourt">{hy?'Ֆուդկորտ':'Фудкорт'}</option><option value="other">{hy?'Այլ':'Другое'}</option></select></label><button className="gold" type="submit">{hy?'Ստանալ խորհրդատվություն':'Получить консультацию'} <Send size={16}/></button></form>}<div className="quick-contact"><a href="tel:+37400000000"><Phone size={15}/>{hy?'Զանգահարել':'Позвонить'}</a><span/><a href="#contact"><MessageCircle size={15}/>WhatsApp</a></div><small>{hy?'Հեռախոսահամարը և WhatsApp-ը կփոխարինենք իրական կոնտակտներով հրապարակումից առաջ։':'Телефон и WhatsApp заменим на реальные контакты перед публикацией.'}</small></div>}
