import {useEffect,useState} from 'react';import {ArrowRight,Check,MessageCircle,Phone,Send} from 'lucide-react';
const services=[
{code:'01',name:'Poster POS',img:'https://s.yimg.com/ny/api/res/1.2/nmP1EEiqPX46VOgDswMnlw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyNDI7aD02OTk-/https%3A/media.zenfs.com/en/verdict_food_service_772/e5471c843b943ef9a3964e961061024b',ru:'Автоматизация ресторана: зал, столы, кухня, пречеки и управление продажами.',hy:'Ռեստորանի ավտոմատացում՝ սրահ, սեղաններ, խոհանոց, նախահաշիվներ և վաճառքի կառավարում։'},
{code:'02',name:'HDM / ՀԴՄ',img:'https://www.tsishop.com/cdn/shop/files/Epson-TM-m30II_112_bluetooth_ethernet_lan_usb_06.jpg?v=1724770824&width=533',ru:'Фискализация продажи напрямую в рабочем процессе кассы.',hy:'Վաճառքի ֆիսկալացում անմիջապես դրամարկղի աշխատանքային հոսքում։'},
{code:'03',name:'IDRAM QR',img:'https://images.squarespace-cdn.com/content/v1/6927d5c4a1ba6e09eea41a75/8f284894-6937-4583-a054-337392b1c058/Firefly_Gemini%2BFlash_order%2Bfood%2Bfrom%2Bphone%2BQR%2Bcode%2Bat%2Ba%2Bhotel%2Blobby%2B329068.png',ru:'QR-оплата, связанная с заказом и суммой продажи.',hy:'QR վճարում՝ կապված պատվերի և վաճառքի գումարի հետ։'},
{code:'04',name:'CIA POS Lite',img:'https://s.yimg.com/ny/api/res/1.2/nmP1EEiqPX46VOgDswMnlw--/YXBwaWQ9aGlnaGxhbmRlcjt3PTEyNDI7aD02OTk-/https%3A/media.zenfs.com/en/verdict_food_service_772/e5471c843b943ef9a3964e961061024b',ru:'Лёгкая касса для небольших магазинов и торговых точек.',hy:'Թեթև դրամարկղ փոքր խանութների և առևտրային կետերի համար։'},
{code:'05',name:'ESC/POS Print',img:'https://www.tsishop.com/cdn/shop/files/Epson-TM-m30II_112_bluetooth_ethernet_lan_usb_06.jpg?v=1724770824&width=533',ru:'Печать чеков и пречеков на совместимых термопринтерах.',hy:'Կտրոնների և նախահաշիվների տպագրություն համատեղելի թերմոտպիչներով։'},
{code:'06',name:'API Integration',img:'https://www.thecodahub.com/assets/team-collaboration-Cy8-hdlm.jpg',ru:'Связываем Poster, оплату, фискализацию и ваши внутренние сервисы.',hy:'Միացնում ենք Poster-ը, վճարումները, ֆիսկալացումը և ձեր ներքին ծառայությունները։'},
{code:'07',name:'Mobile Waiter',img:'https://avisameapp.com/assets/img/mesero-app.png',ru:'Официант работает со смартфона: столы, заказы, изменения и пречек прямо в зале.',hy:'Մատուցողը աշխատում է սմարթֆոնից՝ սեղաններ, պատվերներ, փոփոխություններ և նախահաշիվ անմիջապես սրահում։'},
{code:'08',name:'Smart Menu',img:'https://images.squarespace-cdn.com/content/v1/6927d5c4a1ba6e09eea41a75/8f284894-6937-4583-a054-337392b1c058/Firefly_Gemini%2BFlash_order%2Bfood%2Bfrom%2Bphone%2BQR%2Bcode%2Bat%2Ba%2Bhotel%2Blobby%2B329068.png',ru:'QR-меню с калориями и аллергенами: гость отмечает ограничения и быстрее находит подходящие блюда.',hy:'QR մենյու կալորիաներով և ալերգեններով․ հյուրը նշում է սահմանափակումները և արագ գտնում համապատասխան ուտեստները։'}];
const PHONE_DISPLAY='+374 98 615 005',PHONE_TEL='+37498615005',WHATSAPP='https://wa.me/37498615005';
function useLang(){const [lang,setLang]=useState<'ru'|'hy'>(()=>document.documentElement.lang==='hy'?'hy':'ru');useEffect(()=>{const o=new MutationObserver(()=>setLang(document.documentElement.lang==='hy'?'hy':'ru'));o.observe(document.documentElement,{attributes:true,attributeFilter:['lang']});return()=>o.disconnect()},[]);return lang}
export function ServicesDetail(){const lang=useLang(),hy=lang==='hy';return <section className="service-detail" id="services-detail"><div className="service-detail-head"><span className="eyebrow">CIA SOFT · SERVICES 0.2</span><h2>{hy?'Մեկ համակարգ։ Ութ գործիք։':'Одна система. Восемь инструментов.'}</h2><p>{hy?'Դրամարկղից և ՀԴՄ-ից մինչև մատուցողի սմարթֆոնն ու խելացի QR մենյուն՝ միացնում ենք միայն այն, ինչ պետք է ձեր բիզնեսին։':'От кассы и HDM до смартфона официанта и умного QR-меню — подключаем только то, что действительно нужно вашему бизнесу.'}</p></div><div className="service-list">{services.map(s=><article key={s.code} className={s.code==='07'||s.code==='08'?'service-new':''}><img className="service-photo" src={s.img} alt="" loading="lazy" referrerPolicy="no-referrer"/><span>{s.code}</span><strong>{s.name}</strong><p>{s[lang]}</p><Check size={16}/>{(s.code==='07'||s.code==='08')&&<i>{hy?'ՆՈՐ':'NEW'}</i>}</article>)}</div><a className="service-cta" href="#contact">{hy?'Հավաքել իմ համակարգը':'Собрать мою систему'} <ArrowRight size={16}/></a></section>}
export function ContactForm(){const lang=useLang(),hy=lang==='hy';const [sent,setSent]=useState(false);const submit=(e:React.FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget),business=String(fd.get('business')||''),phone=String(fd.get('phone')||''),type=String(fd.get('type')||'');const labels:Record<string,string>={restaurant:hy?'Ռեստորան / սրճարան':'Ресторан / кафе',retail:hy?'Խանութ':'Магазин',foodcourt:hy?'Ֆուդկորտ':'Фудкорт',other:hy?'Այլ':'Другое'};const message=hy?`Բարև CIA SOFT։%0AԲիզնես՝ ${encodeURIComponent(business)}%0AՀեռախոս՝ ${encodeURIComponent(phone)}%0AՏեսակ՝ ${encodeURIComponent(labels[type]||type)}%0AՑանկանում եմ խորհրդատվություն։`:`Здравствуйте, CIA SOFT.%0AБизнес: ${encodeURIComponent(business)}%0AТелефон: ${encodeURIComponent(phone)}%0AТип: ${encodeURIComponent(labels[type]||type)}%0AХочу получить консультацию.`;setSent(true);window.open(`${WHATSAPP}?text=${message}`,'_blank','noopener,noreferrer')};return <div className="lead-panel"><span className="eyebrow">CONTACT 0.2</span><h3>{hy?'Ստանալ առաջարկ ձեր բիզնեսի համար':'Получить решение для вашей точки'}</h3><p>{hy?'Թողեք կոնտակտը։ Կքննարկենք ձեր ընթացիկ համակարգը և կառաջարկենք անհրաժեշտ կազմը։':'Оставьте контакт. Обсудим вашу текущую систему и предложим нужную конфигурацию.'}</p>{sent?<div className="lead-success"><Check/><strong>{hy?'WhatsApp-ը բացված է':'WhatsApp открыт'}</strong><span>{hy?'Ստուգեք պատրաստ հաղորդագրությունը և ուղարկեք այն CIA SOFT-ին։':'Проверьте подготовленную заявку и отправьте её CIA SOFT.'}</span></div>:<form onSubmit={submit}><label>{hy?'Բիզնեսի անվանումը':'Название бизнеса'}<input required name="business" placeholder={hy?'Օր. My Cafe':'Например, My Cafe'}/></label><label>{hy?'Հեռախոս':'Телефон'}<input required name="phone" inputMode="tel" placeholder="+374 __ ___ ___"/></label><label>{hy?'Բիզնեսի տեսակը':'Тип бизнеса'}<select name="type" defaultValue="restaurant"><option value="restaurant">{hy?'Ռեստորան / սրճարան':'Ресторан / кафе'}</option><option value="retail">{hy?'Խանութ':'Магазин'}</option><option value="foodcourt">{hy?'Ֆուդկորտ':'Фուդկորտ'}</option><option value="other">{hy?'Այլ':'Другое'}</option></select></label><button className="gold" type="submit">{hy?'Ուղարկել WhatsApp-ով':'Отправить в WhatsApp'} <Send size={16}/></button></form>}<div className="quick-contact"><a href={`tel:${PHONE_TEL}`}><Phone size={15}/>{PHONE_DISPLAY}</a><span/><a href={WHATSAPP} target="_blank" rel="noreferrer"><MessageCircle size={15}/>WhatsApp</a></div><small>{hy?'CIA SOFT · Երևան, Հայաստան':'CIA SOFT · Ереван, Армения'}</small></div>}
